### ISSUE TITLE
Raport, identyfikator IIP

### ISSUE THREAD

**Issue by maras61** [GlownyUrzadGeodezjiIKartografii/WalidatorPlikowGML#1]
(PL)
Dla większej użyteczności raport walidacji powinien zawierać identyfikatory IIP obiektów wskazanych jako błędne.
Pozwoliłoby to wręcz na pewną automatyzację procesu korekty błedów.
(ENG)
For greater usability, the validation report should contain the IIP identifiers of the objects indicated as erroneous.
This would even allow some automation of the error correction process.

**Comment by GlownyUrzadGeodezjiIKartografii** [comment]
Od wersji 1.0.7 raportowany jest gml:id zarówno do xls lub pdf jak również do warstw QGIS wskazujących błędne obiekty.
