### ISSUE TITLE
Wybór formatu raportu wpływa wynik walidacji

### ISSUE THREAD

**Issue by Gor1nV** [GlownyUrzadGeodezjiIKartografii/WalidatorPlikowGML#10]
Dzień dobry,

W dniu dzisiejszym przeprowadzałem kontrole na pliku GML zawierającym dane bazy GESUT.
Plik ten miał w sobie błędy atrybutów, bez błędów geometrii.
W przypadku wybrania formatu raportu **XLS otrzymywałem negatywny** wynik walidacji.
Pierwszy arkusz wynikowego pliku XLS (Raport z walidacji) nie zawiera wierszy błędów, drugi natomiast (Raport z kontroli atrybutów) zawiera takowe.

W przypadku wybrania formatu raportu **TXT otrzymywałem pozytywny** wynik walidacji.
W pliku TT widnieje sekcja "KONTROLE ATRYBUTÓW" z wypisanymi błędami.

W mojej opinii wynik walidacji pliku GML zawierającego dane bazy GESUT nie powinien być zależny od wybranego formatu zapisu raportu z walidacji.

**Comment by GlownyUrzadGeodezjiIKartografii** [comment]
Aktualna wersja wtyczki nie zawiera formatu raportu TXT.
