### ISSUE TITLE
Błąd - Szablon kontroli BDOT10k wersja szablonu 1.0.3 - topo_e2_k61_1

### ISSUE THREAD

**Issue by kStachura** [GlownyUrzadGeodezjiIKartografii/WalidatorPlikowGML#11]
Dzień dobry,
W szablonie kontroli BDOT10k ver 1.0.3 - @id topo_e2_k61_1 zawiera spację, a warunek @sql za wieżą ciśnień zawiera nieprawidłowy znak który nie jest apostrofem. 
Proszę o poprawę,
Pozdrawiam,
Karol Stachura

**Comment by GlownyUrzadGeodezjiIKartografii** [comment]
Poprawiono szablon kontroli. Nowa wersja szablonu - 1.0.4 będzie dostępna we wtyczce w wersji 1.0.6.
