### ISSUE TITLE
Walidator nie uwzględnia końca wersji obiektów - BDOT10k

### ISSUE THREAD

**Issue by kStachura** [GlownyUrzadGeodezjiIKartografii/WalidatorPlikowGML#12]
Dzień dobry,
Testy kontroli walidatorem w wersji  1.0.5. dla BDOT10k wskazują, że walidator kontroluje dane z występującym końcem wersji obiektu (usunięte). 
Proszę o dodanie opcji - brak kontroli dla obiektów usuniętych.
Pozdrawiam,
Karol Stachura

**Comment by GlownyUrzadGeodezjiIKartografii** [comment]
Od wersji 1.0.6 walidatora kontrola działa tylko dla aktualnych obiektów.
