### ISSUE TITLE
Raport txt walidatora - BDOT10k

### ISSUE THREAD

**Issue by kStachura** [GlownyUrzadGeodezjiIKartografii/WalidatorPlikowGML#14]
Proszę w miarę możliwości o zmianę znaku delimitera raportu txt walidatora z "," na inny lub usunięcie z opisu kodów błędów w szablonie kontroli dla BDOT10k znaku "," dla poniższych warunków
topo_e1_k7_1 Brak wysokości wału przeciwpowodziowego lub grobli, nasypu
topo_e1_k7_3 Brak szerokości podstawy wału przeciwpowodziowego lub grobli, nasypu
topo_e1_k7_3 Brak szerokości korony wału przeciwpowodziowego lub grobli, nasypu
topo_e3_k6 Błędy pełnego pokrycia (braki, nakładanie) w kategorii PT
topo_e3_k155 Długość obiektu 'falochron','ostroga' w OT_BUUO_L mniejsza niż 10 m
topo_e4_k11_1 Błąd formatu atrybutu wysokość OT_RTPW_P - dół, kopiec lub hałda
topo_e4_k13 Błąd formatu atrybutu wysokość OT_RTLW_L - skarpa, wąwozów
topo_e4_k27 Istnieją obiekty, które mają nadmierną liczbę werteksów

**Comment by GlownyUrzadGeodezjiIKartografii** [comment]
Poprawiono szablon kontroli. Nowa wersja szablonu - 1.0.4 będzie dostępna we wtyczce w wersji 1.0.6.

**Comment by GlownyUrzadGeodezjiIKartografii** [comment]
Wersja 1.0.7 nie posiada już funkcji raportowania do plików txt.
