### ISSUE TITLE
topo_e1_k33_1 Brak atrybutu  identyfikatorSIMC - BDOT10k

### ISSUE THREAD

**Issue by kStachura** [GlownyUrzadGeodezjiIKartografii/WalidatorPlikowGML#15]
Kod błędu w szablonie kontroli topo_e1_k33_1 dla BDOT10k wskazuje na potrzebę dopisania identyfikatoraSIMC dla wszystkich placów. W mojej ocenie zapis identyfikatora zarówno SIMC jak  i TERC powinien być stosowany do placów, które mają nazwę. Podejście że do każdego placu należy dopisać identyfikator miejscowości na której leży będzie powodowało, że w przypadku gdy plac nie leży w jednej miejscowości należy dodatkowo go posegmentować. Segmentacja taka może spowodować że część takiego placu nie będzie spełniała warunków powierzchniowych czyli będzie poniżej 1000m2 co spowoduje wystąpienie błędu topo_e3_k167. Proszę o modyfikację tego warunku tak, żeby id miejscowości wymagane było tylko dla nazwanych placów. Informację o miejscowości na jakiej leży plac każdy użytkownik może pozyskać wykonując analizę przestrzenną z warstwą OT_ADMS_A.

**Comment by GlownyUrzadGeodezjiIKartografii** [comment]
Poprawiono szablon kontroli. Nowa wersja szablonu - 1.0.4 będzie dostępna we wtyczce w wersji 1.0.6.
