### ISSUE TITLE
topo_e3_k123  Błędna geometria (np. zdublowane werteksy lub samoprzecięcia) w klasie OT_SKRP_L - BDOT10k

### ISSUE THREAD

**Issue by kStachura** [GlownyUrzadGeodezjiIKartografii/WalidatorPlikowGML#16]
Wykazane przez walidator błędy geometrii nie są potwierdzane zarówno przez narzędzia Qgis 
Wektor > Narzędzia Geometrii > Sprawdź poprawność
jak i bazę Postgis: 
select * from ot_skrp_l where st_isvalid(ot_skrp_l.geometria) = false;
Proszę o weryfikację funkcji sprawdzających geometrię dla tego błędu oraz analizę dla funkcji kontrolujących geometrię dla pozostałych warstw BDOT10k.

**Comment by GlownyUrzadGeodezjiIKartografii** [comment]
W wersji 1.0.9 dodano kontrole geometrii metodami: 1 QGIS oraz metodą 2 GEOS zgodnie z dokumentacją QGIS -
https://docs.qgis.org/3.34/en/docs/user_manual/processing_algs/qgis/vectorgeometry.html#check-validity
Proszę o wskazanie zbioru, na którym wychodziły niepotwierdzone błędy, jakich klas to dotyczyło oraz jakie błędy były raportowane.
