### ISSUE TITLE
topo_e4_k24 - BDOT10k 

### ISSUE THREAD

**Issue by kStachura** [GlownyUrzadGeodezjiIKartografii/WalidatorPlikowGML#17]
W kontroli topo_e4_k24 dla szablonu kontroli BDOT10k wywoływana jest funkcja czyPrzecinaGranicePowiatuDlugoscPonizej50m która próbuje pobrać z dysku plik zapisany w ścieżce c:\powiaty.shp zapisany domyślnie w pliku walidator_plikow_gml.ini.
Qgis zgłasza błąd w sterowniku ogr nie istnienia tej ścieżki.

**Comment by GlownyUrzadGeodezjiIKartografii** [comment]
Należy w pliku walidator_plikow_gml.ini wpisać ścieżkę do pliku powiaty.shp
