### ISSUE TITLE
Błędy w działaniu wtyczki - BDOT10k OT_SKDR_L

### ISSUE THREAD

**Issue by kStachura** [GlownyUrzadGeodezjiIKartografii/WalidatorPlikowGML#18]
W trakcie prób walidacji aktualnej warstwy powiatu bytowskiego dla BDOT10k pobranej z geoportalu wystąpiły błędy Pythona we wtyczce walidator GUGiK
 
![image](https://github.com/GlownyUrzadGeodezjiIKartografii/WalidatorPlikowGML/assets/107627202/f33ad547-d723-4f9e-a719-1fb3e121539e)

Wtyczka nie raportuje błędów Pythona w oknie użytkownika, widać je tylko jeśli użytkownik ma otwarte okno komunikatów Qgis.

**Comment by GlownyUrzadGeodezjiIKartografii** [comment]
Od wersji 1.0.6 walidatora błędu nie zaobserwowano.
