### ISSUE TITLE
nieczytelne komunikaty i opisy błędów

### ISSUE THREAD

**Issue by jdusza1** [GlownyUrzadGeodezjiIKartografii/WalidatorPlikowGML#2]
Komunikaty i opisy błędów w raporcie są bardzo ogólne. "Element jest nieoczekiwany. Zawartość elementu jest niezgodna ze schematem aplikacyjnym. Błąd może być spowodowany m.in. niepoprawną przestrzenią nazw." w praktyce oznacza, że brakuje elementu wcześniejszego niż wymieniony treści błędu, element się powtarza albo nazwa elementu jest niezgodna ze schematem. Komunikaty są niezrozumiałe bez analizy diagramów UML i kodu pliku GML.

**Comment by GlownyUrzadGeodezjiIKartografii** [comment]
Poprawiono opisy komunikatów w wersji 1.1.1.
