### ISSUE TITLE
Szablon kontroli topo_e2_k17 i topo_e2_k18 - BDOT10k

### ISSUE THREAD

**Issue by kStachura** [GlownyUrzadGeodezjiIKartografii/WalidatorPlikowGML#20]
Warunki dla kodu topo_e2_k17 i topo_e2_k18 pokrywają się przy tunelu równym 25m

**Comment by GlownyUrzadGeodezjiIKartografii** [comment]
Poprawiono szablon kontroli. Nowa wersja szablonu - 1.0.4 będzie dostępna we wtyczce w wersji 1.0.6.

**Comment by GlownyUrzadGeodezjiIKartografii** [comment]
Błąd został poprawiony.
