### ISSUE TITLE
Błąd składni zapytania szablon kontroli - BDOT10k 1.0.3

### ISSUE THREAD

**Issue by kStachura** [GlownyUrzadGeodezjiIKartografii/WalidatorPlikowGML#21]
Dzień dobry,
W kodach topo_e2_k45, topo_e2_k46, topo_e2_k47, topo_e2_k48 szablonu kontroli 1.0.3 występują błędy składni. Brak prawidłowego zamknięcia nawiasów we wszystkich warunkach.
Pozdrawiam,
Karol Stachura

**Comment by GlownyUrzadGeodezjiIKartografii** [comment]
Poprawiono szablon kontroli. Nowa wersja szablonu - 1.0.4 będzie dostępna we wtyczce w wersji 1.0.6.

**Comment by GlownyUrzadGeodezjiIKartografii** [comment]
Błąd został poprawiony.
