### ISSUE TITLE
Szablon Kontroli BDOT10k 1.0.4 - topo_e2_k61_1

### ISSUE THREAD

**Issue by kStachura** [GlownyUrzadGeodezjiIKartografii/WalidatorPlikowGML#22]
W warunku występuje nieprawidłowy znak po wieża ciśnień - błąd wykonania sql przez bazę. 
Pozdrawiam,
Karol Stachura

**Comment by GlownyUrzadGeodezjiIKartografii** [comment]
poprawione - szablon 1.0.6
