### ISSUE TITLE
Szablon Kontroli BDOT10k 1.0.4 - topo_e1_k117, topo_e1_k118, topo_e1_k119, topo_e1_k120

### ISSUE THREAD

**Issue by kStachura** [GlownyUrzadGeodezjiIKartografii/WalidatorPlikowGML#23]
W schemacie XSD dla BDOT10k mamy w słowniku "Centralny Rejestr Form Ochrony Przyrody" - w języku XML wielkość znaków ma znaczenie, proszę o poprawę na wielkość znaków tożsamą ze słownikiem XSD.

**Comment by GlownyUrzadGeodezjiIKartografii** [comment]
poprawione - szablon 1.0.6
