### ISSUE TITLE
Szablon kontroli 1.0.4 BDOT10k - topo_e3_k191_17, topo_e3_k191_18, topo_e3_k191_19, topo_e3_k191_20 Nadmierna segmentacja

### ISSUE THREAD

**Issue by kStachura** [GlownyUrzadGeodezjiIKartografii/WalidatorPlikowGML#24]
Stwierdzenie nadmiernej segmentacji w geometriach, które są pobierane z referencji czyli CRFOP będzie oznaczać że źródłem danych tej geometrii po poprawie nie będzie mogła być tożsama z tą z CRFOP. Proszę o analizę czy ta kontrola jest konieczna biorąc pod uwagę potencjalną ilość problemów związaną z wymianą obiektów z CRFOP.
pozdrawiam,
Karol Stachura

**Comment by GlownyUrzadGeodezjiIKartografii** [comment]
poprawione - szablon 1.0.6
