### ISSUE TITLE
Szablon Kontroli BDOT10k 1.0.4 - topo_e3_k191_1

### ISSUE THREAD

**Issue by kStachura** [GlownyUrzadGeodezjiIKartografii/WalidatorPlikowGML#25]
Usunięcie nadmiernej segmentacji na obiektach pobieranych z PRG dla warstwy OT_ADJA_A sprawi że geometria będzie niezgodna z referencją z PRG.
pozdrawiam,
Karol Stachura

**Comment by GlownyUrzadGeodezjiIKartografii** [comment]
poprawione - szablon 1.0.6
