### ISSUE TITLE
Schemat BDOT500 - niezgodność ze schematem z repozytorium interoperacyjności

### ISSUE THREAD

**Issue by kStachura** [GlownyUrzadGeodezjiIKartografii/WalidatorPlikowGML#26]
Schemat XSD o nazwie BDOT500_1.3tech dla BDOT500 w walidatorze w wersji 1.0.6 jest niezgodny z tym opublikowanym w repozytorium interoperacyjności. 
http://crd.gov.pl/pi_referencja/Glowny_Urzad_Geodezji_i_Kartografii/Systemy_BDOT500/BDOT500.NG.OiL.022.54.2021/5/
Jeśli potrzebne są dodatkowe warunki to albo nowy schemat powinien być opublikowany w repozytorium jako obowiązujący albo dodatkowe warunki powinny zostać zapisane w jako elementy modelu jakości w szablonie kontroli.
pozdrawiam,
Karol Stachura

**Comment by GlownyUrzadGeodezjiIKartografii** [comment]
BDOT500_1.3tech jest technicznym schemat wtyczki i nie musi być zgodny z tym opublikowanym w repozytorium interoperacyjności. Źródłem obowiązujących schematów jest repozytorium interoperacyjności.
