### ISSUE TITLE
Brak możliwości wybrania więcej niż 1 pliku do kontroli - wersja 1.0.7

### ISSUE THREAD

**Issue by kStachura** [GlownyUrzadGeodezjiIKartografii/WalidatorPlikowGML#30]
Dzień dobry,
Brak jest możliwości wybrania więcej niż jednego pliku xml do kontroli w przypadku BDOT10k.

**Comment by MarcinLebiecki** [comment]
Aby skontrolować kilka plików xml należy spakować pliki do zip i wskazać plik zip.

**Comment by GlownyUrzadGeodezjiIKartografii** [comment]
Aby skontrolować kilka plików xml należy spakować pliki do zip i wskazać plik zip.
