### ISSUE TITLE
Crash wtyczki przy próbe wybrania spakowanej paczki danych

### ISSUE THREAD

**Issue by kStachura** [GlownyUrzadGeodezjiIKartografii/WalidatorPlikowGML#31]
W przypadku wybierania spakowanej paczki danych BDOT10k z powiatu m. Gdańsk pobranej z geoportalu z kontrolami dodatkowymi wtyczka powoduje crash Qgis.

**Comment by GlownyUrzadGeodezjiIKartografii** [comment]
Poprawiono mechanizm wczytywania danych w wersji 1.0.9.
