### ISSUE TITLE
Błąd w oknie zakładka formaty raportów

### ISSUE THREAD

**Issue by kStachura** [GlownyUrzadGeodezjiIKartografii/WalidatorPlikowGML#32]
Zakładka Formaty raportów pozwala nie wybrać żadnej opcji zapisu formatu co powoduje zakończenie działania wtyczki.

**Comment by GlownyUrzadGeodezjiIKartografii** [comment]
Poprawione w wersji 1.0.9. Należy wskazać jeden lub obydwa formaty raportu, aby uruchomić proces.
