### ISSUE TITLE
Atrybut 'polozenie' ma pustą wartość dla obiektów o rodzaju 'j'.

### ISSUE THREAD

**Issue by SlawomirRybarczyk** [GlownyUrzadGeodezjiIKartografii/WalidatorPlikowGML#33]
Atrybut 'polozenie' ma pustą wartość dla obiektów o rodzaju 'j'. Błąd jest zgłaszany mimo tego, że w pliku atrybut tez został uzupełniony.

<ot:OT_Komunikacja gml:id="PL.PZGiK.4043.BDOT500_E083608F-6BE9-45CA-9E46-282A2A3ADEFD_2020-10-15T12-56-35">
<gml:identifier codeSpace="http://iip.gov.pl">urn:pzgik:id:PL.PZGiK.4043.BDOT500:E083608F-6BE9-45CA-9E46-282A2A3ADEFD:2020-10-15T12:56:35</gml:identifier>
<ot:idIIP>
<ot:OT_IdentyfikatorIIP>
<ot:lokalnyId>E083608F-6BE9-45CA-9E46-282A2A3ADEFD</ot:lokalnyId>
<ot:przestrzenNazw>PL.PZGiK.4043.BDOT500</ot:przestrzenNazw>
<ot:wersjaId>2020-10-15T12:56:35</ot:wersjaId>
</ot:OT_IdentyfikatorIIP>
</ot:idIIP>
<ot:startObiekt>2014-11-12T09:05:32</ot:startObiekt>
<ot:startWersjaObiekt>2020-10-15T12:56:35</ot:startWersjaObiekt>
<ot:zrodlo>D</ot:zrodlo>
<ot:numerOperatu>P.2471.2014.363</ot:numerOperatu>
<ot:geometria>
<gml:Polygon gml:id="pg1_obj_id_4263220" srsName="urn:ogc:def:crs:EPSG::2177" srsDimension="2">
<gml:exterior>
<gml:LinearRing>
<gml:posList srsDimension="2"> 5583665.67815688 6566842.33303845 5583661.40983419 6566857.81387488 5583654.65273792 6566882.92289132 5583652.04618658 6566891.9286643 5583650.91360588 6566895.89792536 5583647.78395964 6566904.45334311 5583642.76568349 6566917.2742081 5583641.96653504 6566919.08172188 5583636.52178063 6566932.29045882 5583632.29163853 6566942.16620488 5583628.27496474 6566952.22108904 5583621.42476774 6566968.67781122 5583618.0256525 6566981.29233929 5583615.69493248 6566990.11404239 5583614.99571925 6566993.00794086 5583621.48804329 6566991.44871525 5583622.24341902 6566987.51930493 5583623.76736523 6566980.08032527 5583624.7198264 6566976.83772343 5583627.97493529 6566968.65335802 5583634.69009782 6566951.40152363 5583639.7501537 6566938.89454124 5583646.85899976 6566921.43290474 5583648.49 6566917.08 5583659.94 6566884.02 5583665.05936059 6566863.96729177 5583668.77850674 6566849.1282229 5583670.34583351 6566849.68805962 5583672.14 6566843.89 5583670.23 6566843.33 5583669.69 6566843.79 5583665.67815688 6566842.33303845</gml:posList>
</gml:LinearRing>
</gml:exterior>
</gml:Polygon>
</ot:geometria>
<ot:rodzajObiektu>j</ot:rodzajObiektu>
<ot:polozenie>0</ot:polozenie>
</ot:OT_Komunikacja>

**Comment by GlownyUrzadGeodezjiIKartografii** [comment]
Dziękujemy za zgłoszenie. Po przeanalizowaniu problemu stwierdziliśmy, że walidator zgłasza błąd dla atrybutu „polozenie”, ponieważ został on określony jako 0, co jest niezgodne z rozporządzeniem EGiB. Zgodnie z przepisami, atrybut „polozenie” dla obiektów o rodzaju 'j' nie może mieć wartości pustej ani równej 0. Błąd przestanie się pojawiać po wprowadzeniu odpowiedniej wartości zgodnej z wymogami rozporządzenia.
