### ISSUE TITLE
Brak dokumentacji do produktu

### ISSUE THREAD

**Issue by kStachura** [GlownyUrzadGeodezjiIKartografii/WalidatorPlikowGML#34]
Dzień dobry, 
Uprzejmie proszę o dołączenie do produktu dokumentacji:
- użycia wtyczki np. z opisem dołączenia pliku z powiatami i jego strukturą, struktury zip, ..... 
-  szablonów kontroli - wersjonowana  dokumentacja warunków kontroli dla wszystkich typów danych (BDOT500, GESUT, EGiB, BDOT10k. ...) Obecnie używane funkcje czy kontrole kodów wymagają od użytkowników sprawdzania w xml na warunkach szablonu o co może chodzić. Nie każdy może i chce to robić. Dlatego potrzebna jest dokumentacja użytkownika o co w danym błędzie chodzi.
Pozdrawiam,
Karol Stachura

**Comment by GlownyUrzadGeodezjiIKartografii** [comment]
Dokumentacja użytkownika będzie dostępna w wersji 1.1.0. Wprowadzono changlog do szablonu kontroli dla BDOT10k we wtyczce w wersji 1.0.9. Dla pozostałych baz changelog będzie wprowadzony w wersji 1.1.0.

**Comment by kStachura** [comment]
Przepraszam ale nie rozumiem idei zamykania zgłoszeń na podstawie deklaracji nie umieszczonych w produkcie. Zgłoszenia braku dokumentacji powinny być utrzymywane jako otwarte do momentu do którego ww. dokumentacja znajdzie się w produkcie.
