### ISSUE TITLE
nadmiarowe raportowanie błędów BDOT10k

### ISSUE THREAD

**Issue by DariuszPerkowskiInterTIM** [GlownyUrzadGeodezjiIKartografii/WalidatorPlikowGML#35]
- raportowane są w SKDR braki szerokości nawierzchni gruntowych, której się nie pozyskuje
- raportowane są braki geometrii przy granicy powiatu nie uwzględniające zaokrąglenia punktów lub uwzględniony jest mniejszy bufor tolerancji niż w poprzednich opracowaniach (0,1m)
- w kontrolach o nadmiernej segmentacji w raporcie wykazywane są obiekty stykające się jednym werteksem

**Comment by GlownyUrzadGeodezjiIKartografii** [comment]
Błędy poprawione - od szablonu  1.0.7 dostępnego we wtyczce w wersji 1.0.9
