### ISSUE TITLE
Przekierowanie opisu błędu z forum Qgis - wtyczka walidator GUGiK

### ISSUE THREAD

**Issue by kStachura** [GlownyUrzadGeodezjiIKartografii/WalidatorPlikowGML#36]
Dzień dobry,
Na forum Qgis pojawił się błąd z kodem wskazującym na kod wtyczki GUGiK, który przekierowuję tutaj 
http://forum.quantum-gis.pl/thread-2076.html

Proszę o rozwiązanie problemu zgłoszonego przez użytkownika forum, obraz z opisem poniżej.

![zgloszenie](https://github.com/user-attachments/assets/06bb6227-19ec-4fb4-b6da-6c207b71b612)

Pozdrawiam,

**Comment by GlownyUrzadGeodezjiIKartografii** [comment]
Rozwiązano problem zgłoszony przez użytkownika. Błąd został wyjaśniony z użytkownikiem.
