### ISSUE TITLE
Brak aktywności przycisku OK

### ISSUE THREAD

**Issue by kStachura** [GlownyUrzadGeodezjiIKartografii/WalidatorPlikowGML#37]
Dzień dobry,
W wersji 1.0.9 po wskazaniu danych BDOT10k w pliku zip i zakresu kontroli przycisk ok uruchamiający kontrolę jest nieaktywny.
Tym samym w chwili obecnej nie jesteśmy w stanie kontrolować danych BDOT10k w tym obecnie prowadzonych zamówień publicznych tym narzędziem.

**Comment by DariuszPerkowskiInterTIM** [comment]
Dzień dobry,
trzeba wgrać granice w GML'ach i dopiero będzie aktywny. Wcześniejsza wersja pozwalała puścić kontrole bez tego.
Pozdrawiam

**Comment by GlownyUrzadGeodezjiIKartografii** [comment]
W wersji 1.1.0 dodana zostanie dokumentacja, która opisuje w/w sytuację.
