### ISSUE TITLE
Walidacji BDOT500 w wersji 1.0.9

### ISSUE THREAD

**Issue by SP-gis** [GlownyUrzadGeodezjiIKartografii/WalidatorPlikowGML#39]
W najnowszej wersji 1.0.9 po wczytaniu pliku zawierającego bazę BDOT500 przycisk OK jest nieaktywny. Nie można uruchomić walidacji

**Comment by MarcinLebiecki** [comment]
Opisany w zgłoszeniu błąd nie występuje. Przycisk OK jest aktywny i można przeprowadzić walidację.

**Comment by GlownyUrzadGeodezjiIKartografii** [comment]
Opisany w zgłoszeniu błąd nie występuje. Przycisk OK jest aktywny i można przeprowadzić walidację.
