### ISSUE TITLE
rodzaj nawierzchni i położenie - baza BDOT500

### ISSUE THREAD

**Issue by jdusza1** [GlownyUrzadGeodezjiIKartografii/WalidatorPlikowGML#4]
Wartości atrybutów "Rodzaj Nawierzchni" i "położenie" są sprawdzane dla wszystkich obiektów z kategorii komunikacja. Według przepisów rozporządzenia bdot500 rodzaj nawierzchni jest wymagany tylko dla jezdni i chodników, a położenie tylko dla jezdni. Zaten dla pozostałych obiektów może pozostać pusty.

**Comment by GlownyUrzadGeodezjiIKartografii** [comment]
Dziękujemy za zgłoszenie. Informuję, że plik z szablonem kontroli bazy BDOT500 został dostosowany tak, aby zgodnie z przepisami weryfikował wartości atrybutów wyłącznie dla odpowiednich obiektów. Korekty te zostaną uwzględnione w nowej wersji wtyczki tj. 1.1.0, (będzie udostępniona w sierpniu 2024 r.), dzięki czemu będzie ona w pełni zgodna z rozporządzeniem.
Jeżeli mimo to problem będzie się powtarzał lub wystąpią inne trudności, prosimy o kontakt.
