### ISSUE TITLE
Niezgodność warunku topo_e1_k22 szablonu kontroli BDOT10k 1.0.7 z rozporządzeniem

### ISSUE THREAD

**Issue by kStachura** [GlownyUrzadGeodezjiIKartografii/WalidatorPlikowGML#40]
Warunek dla BDOT10k "topo_e1_k22 Atrybut liczbaJezdniDrogi musi pozostać niewypełniony" jest niezgodny z zapisem Rozporządzenia Ministra Rozwoju, Pracy i Technologii z dnia 27 lipca 2021 r. w sprawie bazy danych obiektów topograficznych oraz bazy danych obiektów ogólnogeograficznych, a także standardowych opracowań kartograficznych (**str 32**), który brzmi dla klasy SKJZ_L i SKDR_L:

"szczegółowy zakres informacji dla klasy obiektów „droga” jest tożsamy z zakresem określonym dla klasy obiektów
„jezdnia” zawartym w tabeli 6, z wyłączeniem pozycji o lp. 9–15." - tym samym w obiekcie SKJZ musi występować atrybut liczbajezdniDrogi z wartością zgodną z SKDR_L.

**Comment by GlownyUrzadGeodezjiIKartografii** [comment]
Informacja w zakresie zgłoszenia została do Pana przekazana drogą mailową w dniu 19.08.2024 r.
