### ISSUE TITLE
Błąd składni zapytania topo_e2_k213_5 - szablon kontroli 1.0.8 BDOT10k

### ISSUE THREAD

**Issue by kStachura** [GlownyUrzadGeodezjiIKartografii/WalidatorPlikowGML#42]
Brak poprawnej składni warunku sql topo_e2_k213_5 - brak apostrofów
Jest 
"kodKarto10k NOT IN (0010_226', '0010_350', '0010_351_1)"
Powinno być 
"kodKarto10k NOT IN ('0010_226', '0010_350', '0010_351_1')"

Ze względu na to, że w dotychczasowych wszystkich wersjach szablonów kontroli BDOT10k zgłosiłem już kilkadziesiąt takich błędów składni będę wdzięczny jeśli GUGiK wdroży testowanie poprawności składni warunków sql i będzie je wykonywał samodzielnie przez opublikowaniem kolejnych szablonów kontroli. Z góry dziękuję.
Pozdrawiam,
Karol Stachura

**Comment by GlownyUrzadGeodezjiIKartografii** [comment]
Błąd został naprawiony w wersji 1.1.1.
