### ISSUE TITLE
Błąd składni warunku topo_e2_k213_12 szablon kontroli 1.0.8 - BDOT10k

### ISSUE THREAD

**Issue by kStachura** [GlownyUrzadGeodezjiIKartografii/WalidatorPlikowGML#43]
Błąd składni warunku sql - brak apostrofu 
jest:
"kodKarto10k NOT IN ('0010_227', '0010_228', '0010_229', '0010_433_1', '0010_433_2', '0010_434)"
powinno być:
"kodKarto10k NOT IN ('0010_227', '0010_228', '0010_229', '0010_433_1', '0010_433_2', '0010_434')"
pozdrawiam,
Karol Stachura

**Comment by GlownyUrzadGeodezjiIKartografii** [comment]
Błąd został naprawiony w wersji 1.1.1.
