### ISSUE TITLE
Warunek topo_e1_k24_6 - wykazuje błąd dla łączników dróg 

### ISSUE THREAD

**Issue by kStachura** [GlownyUrzadGeodezjiIKartografii/WalidatorPlikowGML#44]
W przypadku w którym w SKDR_L występuje linia umowna w informacji dodatkowej np. na rondach warunek dalej zwraca błąd. 
![image](https://github.com/user-attachments/assets/997ae6f5-609e-4e90-82ed-5e66b7319fac)
Pozdrawiam,
Karol Stachura

**Comment by GlownyUrzadGeodezjiIKartografii** [comment]
Błąd został naprawiony w wersji 1.1.1.
