### ISSUE TITLE
Brak wykrycia błędów wersjonowania - BDOT10k

### ISSUE THREAD

**Issue by kStachura** [GlownyUrzadGeodezjiIKartografii/WalidatorPlikowGML#45]
Walidator w wersji 1.1.0 nie raportuje braku zmiany wersji i początku wersji w przypadku zmiany atrybutów obiektu BDOT10k. W załączniku obraz tożsamych wersji obiektu przed i po zmianie bez zmiany wersji która nie została wykryta przez walidator. 
![image](https://github.com/user-attachments/assets/567e64c8-ee33-43c2-a0d3-4eb38412d74d)
![image](https://github.com/user-attachments/assets/15a9e45a-ae81-40c5-ad11-5deb9b2269d1)
Brak wykrycia zmian jest masowy i dotyczy wielu warstw.
Pozdrawiam,
Karol Stachura

**Comment by kStachura** [comment]
Raport w zakresie wykrycia problemów z wersjonowaniem z walidatora dla całego powiatu wygląda tak
![image](https://github.com/user-attachments/assets/dfdc0546-18fa-421a-9683-2f2c677a5690)

**Comment by GlownyUrzadGeodezjiIKartografii** [comment]
Proszę o przesłanie danych oryginalnych i zmienionych do autora wtyczki w celu weryfikacji zgłoszenia.

**Comment by kStachura** [comment]
Proszę o kontakt z Państwa przedstawicielami komisji odbioru, którzy te dane otrzymali. Identyfikacja po lokalnyId w systemie GUGiK chyba nie powinna nastręczać zbytniego kłopotu a powie wszystko o powiecie i obiekcie o który chodzi.

**Comment by GlownyUrzadGeodezjiIKartografii** [comment]
Błąd został naprawiony w wersji 1.1.1.
