### ISSUE TITLE
BDOT500 błąd geometrii

### ISSUE THREAD

**Issue by ejjbamOs** [GlownyUrzadGeodezjiIKartografii/WalidatorPlikowGML#46]
W raporcie z kontroli dodatkowych (wersja walidatora 1.1.0 updated at 29.08.2024 21:15) zgłaszany jest błąd:
"_Geometria obiektu o rodzaju 'b/p/z/i' jest innego typu niż 'powierzchnia'._" dla obiektów, które  geometrie zapisane mają jako **polygon**
Przykładowy obiekt z GML:
`<gml:featureMember>
	<ot:OT_SportIRekreacja gml:id="PL.PZGiK.7014.BDOT_fde5478e-f0d5-4db5-95b2-8c42b50d435c_2024-03-28T01-00-00">
		<ot:idIIP>
			<ot:OT_IdentyfikatorIIP>
				<ot:lokalnyId>fde5478e-f0d5-4db5-95b2-8c42b50d435c</ot:lokalnyId>
				<ot:przestrzenNazw>PL.PZGiK.7014.BDOT</ot:przestrzenNazw>
				<ot:wersjaId>2024-03-28T01:00:00</ot:wersjaId>
			</ot:OT_IdentyfikatorIIP>
		</ot:idIIP>
		<ot:startObiekt>2021-02-06T20:00:00</ot:startObiekt>
		<ot:startWersjaObiekt>2024-03-28T01:00:00</ot:startWersjaObiekt>
		<ot:zrodlo>O</ot:zrodlo>
		<ot:informacjaDodatkowa>Data pomiaru: 31-12-2019; {1258e786-1c9a-4479-b28e-83a17d6e8920}</ot:informacjaDodatkowa>
		<ot:geometria>
			<gml:Polygon gml:id="GEOMETRIA.6ea29944-1d22-416d-b96b-089a462351f5" srsName="urn:ogc:def:crs:EPSG::2177" srsDimension="2">
				<gml:exterior>
					<gml:LinearRing>
						<gml:posList>5893064.29 6511308.11 5893039.24 6511305.82 5893038.43 6511313.53 5893063.51 6511315.83 5893064.29 6511308.11 </gml:posList>
					</gml:LinearRing>
				</gml:exterior>
			</gml:Polygon>
		</ot:geometria>
		<ot:RodzajObiektu>z</ot:RodzajObiektu>
	</ot:OT_SportIRekreacja>
</gml:featureMember>
`

**Comment by GlownyUrzadGeodezjiIKartografii** [comment]
Zweryfikowano zgłoszony błąd. Błąd nie występuje, a szablon kontroli BDOT500 jest poprawny.
