### ISSUE TITLE
Błąd składni topo_e1_k24_6 - szablon kontroli 1.0.9 BDOT10k

### ISSUE THREAD

**Issue by kStachura** [GlownyUrzadGeodezjiIKartografii/WalidatorPlikowGML#47]
Dzień dobry,
W warunku topo_e1_k24_6 występuje błąd składni zapytania:
W warunku sql:

szerokoscNawierzchni IS NULL AND liczbaJezdniDrogi = 1 AND materialNawierzchni != 'grunt naturalny' AND (informacjaDodatkowa IS NULL OR NOT (informacjaDodatkowa LIKE '%linia umowna%' OR uwagi LIKE '%linia umowna%')
Brakuje końcowego nawiasu. 

Po raz kolejny po wskazaniu już kilkudziesięciu tego typu błędów, jak widać na razie bezskutecznie, apeluję o przeprowadzanie przez GUGiK testów parsowania zapytań SQL **przed umieszczeniem** ich we wtyczce **używanej produkcyjnie**.

**Comment by GlownyUrzadGeodezjiIKartografii** [comment]
Poprawione w wersji 1.1.3
