### ISSUE TITLE
Problem z obługą dużych plików

### ISSUE THREAD

**Issue by tompow1** [GlownyUrzadGeodezjiIKartografii/WalidatorPlikowGML#6]
Aplikacja nie obsługuje dużych plików GML (np. 2,60 GB). Próba walidacji takiego pliku kończy się niepowodzeniem z jednym komunikatem w raporcie: "Błąd odczytu pliku '*.gml': nie udało się załadować "*.gml"".
Sprawdzone na kilku bardzo mocnych i wydajnych maszynach.

**Comment by GlownyUrzadGeodezjiIKartografii** [comment]
Proszę o weryfikację na wersji od 1.0.8.
