### ISSUE TITLE
Błędy w kontroli wadlidacji - wersja  1.0.2

### ISSUE THREAD

**Issue by Geoinformatyka** [GlownyUrzadGeodezjiIKartografii/WalidatorPlikowGML#7]
Proszę o informację czego dotyczy błąd walidacji:

1."Element '{ewidencjaGruntowIBudynkow:1.0}dataDokumentu': '' jest nieprawidłową wartością typu podstawowego 'xs:date'."?
2. W kontroli atrybutów występuje błąd: "Geometria jest innego typu niż powierzchnia dla rodzaju obiektu związanego z budynkiem równego t/w/i/s/r/j/d" jedank w bazie danych obiekty te są powierzchniowe (schody)

Proszę o informację zwrotną

Pozdrawiam

**Comment by GlownyUrzadGeodezjiIKartografii** [comment]
Dziękujemy za zgłoszenie. 
Otrzymany błąd o treści: „Element '{ewidencjaGruntowIBudynkow:1.0}dataDokumentu': '' jest nieprawidłową wartością typu podstawowego 'xs:date' - wskazuje na błędnie zapisaną datę lub jej brak w danych GML. Poprawny format daty w plikach GML to YYYY-MM-DD (rok-miesiąc-dzień). Wartość, którą obecnie Państwo podają, jest albo pusta (''), albo niezgodna z tym formatem.
W odpowiedzi na drugie pytanie informuję, że plik z szablonem kontroli bazy BDOT500 został dostosowany, aby zgodnie z przepisami weryfikować wartości atrybutów tylko dla odpowiednich obiektów. Nowa wersja szablonu kontroli będzie dostępna w wersji 1.1.0 wtyczki (opublikowana będzie w sierpniu 2024 r.), co zapewni pełną zgodność z rozporządzeniem.
Jeśli mimo to problem będzie się powtarzał lub wystąpią inne trudności, prosimy o kontakt.
