### ISSUE TITLE
Walidacja plików GML na potrzeby ZSIN

### ISSUE THREAD

**Issue by astaworko** [GlownyUrzadGeodezjiIKartografii/WalidatorPlikowGML#8]
Dzień dobry,
Podczas walidacji plików GML na potrzeby przekazania danych do ZSIN zauważyłem kilka "niesprawności" walidatora.
1. Sama walidacja plików przebiega prawidłowo, jednak przy włączonej kontroli atrybutów system dochodzi do 78% i "wisi", nawet kilka godzin (czyli teoretycznie "wisi" i w ogóle nie idzie dalej). Gdzieś w międzyczasie pojawia się tylko komunikat:
![image](https://github.com/GlownyUrzadGeodezjiIKartografii/WalidatorPlikowGML/assets/127086983/eace9668-85e9-4a92-8585-3719e5adfe52)
Jak mam poprawić błędy atrybutów i geometryczne skoro walidacja nie idzie dalej i nie wiem co to za błędy.
3. Walidacja pliku (280 MB) niezależnie czy z włączoną, czy wyłączoną kontrola atrybutów "wywala" całego QGISa. Po prostu program sam się zamyka.
4.

**Comment by GlownyUrzadGeodezjiIKartografii** [comment]
Proszę o używanie najnowszej wersji 1.0.5.

**Comment by astaworko** [comment]
Dziękuję. Sperawdzę
