### ISSUE TITLE
Kontrola atrybutów

### ISSUE THREAD

**Issue by astaworko** [GlownyUrzadGeodezjiIKartografii/WalidatorPlikowGML#9]
Dzień dobry,
Podczas walidacji plików z bazy BDOT500 występują błędy typu:
"Geometria jest innego typu niż powierzchnia dla rodzaju obiektu równego"
Pomimo, że wskazane obiekty mają prawidłową geometrię.

**Comment by ejjbamOs** [comment]
Dla BDOT500 Walidator zgłasza nieuzasadniony błąd dotyczących **OT_Komunikacja** (_Geometria jest innego typu niż powierzchnia dla rodzaju obiektu równego j/c/g/u/r/s/m/z/w/e/n/a_) - we wszystkich przypadkach rodzaj obiektu jest **z** (przepust) a geometria jest linią - wbrew temu co głosi komunikat błędu jest to poprawna sytuacja.

**Comment by GlownyUrzadGeodezjiIKartografii** [comment]
Dziękujemy za zgłoszenie. Przeprowadziliśmy szczegółową weryfikację pliku z szablonami kontroli z bazy BDOT500. Informuję, że wszystkie napotkane błędy dotyczące niezgodności typu geometrii zostały skorygowane. Korekty te zostaną uwzględnione w kolejnej wersji 1.1.0 wtyczki, która zostanie opublikowana w sierpniu 2024 r. Jeżeli problem będzie się powtarzał lub pojawią się inne trudności, prosimy o kontakt.
